export const DEFAULT_KEYS: Record<string, string> = { forward:'KeyW',back:'KeyS',left:'KeyA',right:'KeyD',jump:'Space',sprint:'ShiftLeft',crouch:'ControlLeft',interact:'KeyE',reload:'KeyR',build:'KeyQ',edit:'KeyF',rotate:'KeyT',material:'KeyG',resetEdit:'KeyV',confirm:'Enter',map:'KeyM',inventory:'Tab',drop:'KeyX',heal:'KeyH',shield:'KeyJ',harvest:'Digit6',slot1:'Digit1',slot2:'Digit2',slot3:'Digit3',slot4:'Digit4',slot5:'Digit5',wall:'KeyZ',floor:'KeyC',ramp:'KeyB',cone:'KeyN',pause:'Escape',fire:'Mouse0',aim:'Mouse2',next:'WheelDown',previous:'WheelUp' };
export const DEFAULT_PAD: Record<string, number> = { jump:0,crouch:1,interact:2,build:3,previous:4,next:5,aim:6,fire:7,map:8,pause:9,sprint:10,edit:11,heal:12,material:13,rotate:14,reload:15 };
export const DEFAULTS = { video:{fps:60,renderScale:1,dynamic:false,fov:85,brightness:1,gamma:1,uiScale:1,stats:true}, graphics:{preset:'High',view:360,shadows:2,shadowResolution:1024,texture:128,filter:4,aa:true,lighting:1,foliage:1,particles:1,effects:1,post:true,grain:0,lens:.25,lod:1}, audio:{master:.65,music:.18,effects:.8,ui:.6,environment:.35,footsteps:.7,weapons:.8,building:.65,storm:.45,mute:false}, mouse:{x:12,y:12,ads:45,scope:30,build:1,edit:1,calibration:1,invert:false,acceleration:0,wheel:'weapons',toggleAim:false,toggleSprint:false,toggleCrouch:true}, controller:{x:50,y:50,ads:45,scope:30,build:1,edit:1,deadzone:.15,curve:'linear',acceleration:0,boost:0,reference:180,assist:.3,vibration:true,preset:'standard'}, touch:{x:50,y:50,ads:50,scope:35,build:1,edit:1,reference:180,size:1,opacity:.75,gyro:false,gyroSensitivity:1,show:'auto',layout:{} as Record<string,{x:number;y:number;size:number;hidden:boolean}>}, gameplay:{bots:23,difficulty:'standard',seed:731,duration:8,autoPickup:true,tutorial:true}, accessibility:{motion:true,shake:true,contrast:false,colorblind:false,subtitles:true,crosshair:'#ffffff'}, keys:{...DEFAULT_KEYS},pad:{...DEFAULT_PAD} };
export type Settings = typeof DEFAULTS;
export const freshSettings = (): Settings => structuredClone(DEFAULTS);
export function mergeSettings(input: unknown): Settings { const d=freshSettings(); if(!input||typeof input!=='object') return d; for(const k of Object.keys(d) as (keyof Settings)[]) { const value=(input as any)[k]; if(value&&typeof value==='object') Object.assign(d[k],value); } return d; }
export function loadSettings(){ try{return mergeSettings(JSON.parse(localStorage.getItem('skybreak-settings-v1')||'null'));}catch{return freshSettings();} }
export function saveSettings(s: Settings){try{localStorage.setItem('skybreak-settings-v1',JSON.stringify(s));return true;}catch{return false;}}
export function bindKey(keys: Record<string,string>,action:string,key:string){const old=keys[action];for(const a in keys)if(keys[a]===key&&a!==action)keys[a]=old;keys[action]=key;}
export function mouseDegrees(counts:number,percent:number,calibration:number){return counts*.15*(percent/50)*calibration;}
export function stickValue(v:number,deadzone:number,curve:string){const a=Math.abs(v);return a<=deadzone?0:Math.sign(v)*Math.pow((a-deadzone)/(1-deadzone),curve==='exponential'?2.2:1);}
export function applyPreset(s:Settings,p:string){const i=['Low','Medium','High','Epic'].indexOf(p);if(i<0)return;s.graphics={...s.graphics,preset:p,view:[220,300,360,500][i],shadows:[0,1,2,2][i],shadowResolution:[512,512,1024,2048][i],texture:[32,64,128,256][i],filter:[1,2,4,8][i],aa:i>0,lighting:i>0?1:.65,foliage:[.3,.6,1,1][i],particles:[.25,.5,1,1.5][i],effects:[.35,.7,1,1][i],post:i>0,lod:[.55,.8,1,1.35][i]};s.video.renderScale=[.7,.85,1,1.15][i];}
